version: "3"
services:
  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 4000:4000
    depends_on:
      - mongo
    links:
      - mongo

  mongo:
    image: mongo
    volumes:
      - ~/www/data:/data/db
    ports:
      - 27017:27017